version: '3.7'
services:
    postgresdb:
        container_name: psql_wizard
        image: postgres:12.1-alpine
        expose:
            - 6553
        ports:
            - 6553:6553
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: xxxxxx
            POSTGRES_DB: dropwizarddb
            POSTGRES_PORT: 6553
    wizard-rest-app:
        container_name: wizard-rest
        image: wizard-rest-app
        build: ./
        ports:
            - 8082:8082