version: '3.7'
services:
  postgresdb:
    container_name: psql_wizard
    image: postgres:12-alpine
    expose:
      - 6552
    ports:
      - 6552:6552
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: xxxxxx
      POSTGRES_DB: dropwizarddb
      POSTGRES_PORT: 6552
  wizard-rest-app:
    container_name: wizard-rest
    image: wizard-rest-app
    build: ./
    ports:
      - 8082:8082
    depends_on:
      - postgresdb