server:
    port: 8083

spring:
    jpa:
        hibernate:
            # Hibernate ddl auto (create, create-drop, validate, update)
            dd-auto: validate
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                temp:
                    use_jdbc_metadata_defaults: false
    datasource:
        url: jdbc:postgresql://127.0.0.1:6551/test2
        username: postgres
        password: xxxxxx
        driver-class-name: org.postgresql.Driver
    flyway:
        enabled: false
#        validate-on-migrate: true

swagg:
    swaggerdemo:
        path: rest-api